graph [
comment "Population network, automatically generated by Graphing tool"
directed  1
id  1
label "Population network...."
node [
id 1175
label " "
defaultAtrribute   1
]
node [
id 1164
label "1"
defaultAtrribute   1
]
node [
id 1165
label "Mix:0.59"
vgj [ 
 shape  "Rectangle"
]
]
node [
id 1166
label "5"
defaultAtrribute   1
]
node [
id 1171
label " "
defaultAtrribute   1
]
node [
id 1167
label " "
defaultAtrribute   1
]
node [
id 1168
label "4"
defaultAtrribute   1
]
node [
id 1172
label " "
defaultAtrribute   1
]
node [
id 1169
label "2"
defaultAtrribute   1
]
node [
id 1173
label " "
defaultAtrribute   1
]
node [
id 1174
label "3"
defaultAtrribute   1
]
edge [
source 1167
target  1165
label "0.120"
]
edge [
source 1175
target  1167
label "0.116"
]
edge [
source 1172
target  1166
label "0.872"
]
edge [
source 1175
target  1164
label "0.204"
]
edge [
source 1167
target  1174
label "0.040"
]
edge [
source 1171
target  1175
label "0.141"
]
edge [
source 1173
target  1168
label "0.219"
]
edge [
source 1171
target  1173
label "0.131"
]
edge [
source 1173
target  1165
label "0.024"
]
edge [
source 1165
target  1169
label "0.025"
]
edge [
source 1172
target  1171
label "0.563"
]

]
